### ISSUE TITLE
ride-sharing location_data.csv

### ISSUE THREAD

**Issue by hzzzzjzyq** [Yuya-Hikima/IJCAI2022-Online-Matching-with-Controllable-Rewards-and-Arrival-Probabilities#1]
Thanks for your good work! how can i get location_data.csv for Ride-sharing

**Comment by Yuya-Hikima** [comment]
I am currently on vacation and will respond on Monday (11/14).
Sorry for the lack of the data.

**Comment by Yuya-Hikima** [comment]
I have added "location_data.csv" in the data folder.
This data was obtained by adding the latitude and longitude of the center of gravity to the taxi zone map file available at https://data.cityofnewyork.us/Transportation/NYC-Taxi-Zones/d3c5-ddgc.

**Comment by hzzzzjzyq** [comment]
thanks for you work!
